run:
  timeout: 5m
  go: '1.24'
  skip-dirs:
    - pkg  # Skip generated protobuf code

linters:
  # Use only fast linters that don't have Go 1.24 compatibility issues
  enable:
    - gofmt
    - goimports
    - errcheck
  disable-all: true

linters-settings:
  errcheck:
    check-blank: false

issues:
  exclude-rules:
    # Exclude protobuf generated files from linting
    - path: '\.pb\.go$'
      linters:
        - all
    - path: '\.pb\.gw\.go$'
      linters:
        - all
    - path: '_grpc\.pb\.go$'
      linters:
        - all
  
  # Don't report issues in vendor or generated code
  exclude-dirs:
    - vendor
    - bin
    - pkg
  
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
